CREATE USER USREMPWS
IDENTIFIED BY U5r3MpWs;

CREATE USER SCHEMPLOYEES
IDENTIFIED BY ScH3mPlOyEeS;

GRANT CREATE TABLE TO SCHEMPLOYEES;

GRANT ALTER ANY TABLE TO SCHEMPLOYEES;

CREATE TABLESPACE tbs_03 
   DATAFILE 'tbs_f03.dbf' SIZE 1000M
   LOGGING;

CREATE SEQUENCE SCHEMPLOYEES.SEQGENDERS
    INCREMENT BY 1
    START WITH 1;

CREATE TABLE SCHEMPLOYEES.GENDERS(
FIGENDERID NUMBER DEFAULT SCHEMPLOYEES.SEQGENDERS.nextval NOT NULL,
FCNAME VARCHAR2(255),
CONSTRAINT PK_GENDERS PRIMARY KEY (FIGENDERID))
TABLESPACE tbs_03;

CREATE SEQUENCE SCHEMPLOYEES.SEQJOBS
    INCREMENT BY 1
    START WITH 1;

CREATE TABLE SCHEMPLOYEES.JOBS(
FIJOBID NUMBER DEFAULT SCHEMPLOYEES.SEQJOBS.nextval,
FCNAME VARCHAR2(255),
FNSALARY NUMBER(9,2),
CONSTRAINT PK_JOBS PRIMARY KEY (FIJOBID))
TABLESPACE tbs_03;

CREATE SEQUENCE SCHEMPLOYEES.SEQEMPLOYEES
    INCREMENT BY 1
    START WITH 1;

CREATE TABLE SCHEMPLOYEES.EMPLOYEES(
FIEMPLOYEESID NUMBER DEFAULT SCHEMPLOYEES.SEQEMPLOYEES.nextval,
FIGENDERID NUMBER,
FIJOBID NUMBER,
FCNAME VARCHAR2(255),
FCLASTNAME VARCHAR2(255),
FDBIRTHDATE DATE,
CONSTRAINT PK_EMPLOYEES PRIMARY KEY(FIEMPLOYEESID),
CONSTRAINT FK_JOBID FOREIGN KEY (FIJOBID) REFERENCES SCHEMPLOYEES.JOBS (FIJOBID),
CONSTRAINT FK_GENDERID FOREIGN KEY (FIGENDERID) REFERENCES SCHEMPLOYEES.GENDERS (FIGENDERID))
TABLESPACE tbs_03;

CREATE SEQUENCE SCHEMPLOYEES.SEQEMPWORKHRS
    INCREMENT BY 1
    START WITH 1;
/
CREATE TABLE SCHEMPLOYEES.EMPLOYEE_WORKED_HOURS(
FIEMPWORKHRSID NUMBER DEFAULT SCHEMPLOYEES.SEQEMPWORKHRS.nextval,
FIEMPLOYEESID NUMBER,
FNWORKED_HOURS NUMBER,
FDWORKED_DATE DATE,
CONSTRAINT PK_EMPWORKHRS PRIMARY KEY (FIEMPWORKHRSID),
CONSTRAINT FK_EMPLOYEE FOREIGN KEY (FIEMPLOYEESID) REFERENCES SCHEMPLOYEES.EMPLOYEES (FIEMPLOYEESID))
TABLESPACE tbs_03;
